# Generated by Django 5.0.6 on 2024-06-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='TeamStatus',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
