# Generated by Django 5.0.6 on 2024-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_team_teamstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='TeamStatus',
            field=models.CharField(choices=[('active', 'Active'), ('relegate', 'Relegate')], default='active', max_length=10),
        ),
    ]
