# Generated by Django 5.0.6 on 2024-06-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_team_teamstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='TeamLogo',
            field=models.ImageField(default='logo2.png', upload_to='teamlogo'),
        ),
    ]
