# Generated by Django 5.0.6 on 2024-06-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_team_teamlogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
