# Generated by Django 4.1.1 on 2024-05-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0003_auto'),
        ('rule', '0004_auto2'),
    ]

    operations = [
    ]
