# Generated by Django 5.0.6 on 2024-08-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('round_number', models.IntegerField(default=1)),
                ('match_stadium', models.CharField(max_length=180)),
                ('home_logo', models.ImageField(default='logo2.png', upload_to='calendar')),
                ('away_logo', models.ImageField(default='logo2.png', upload_to='calendar')),
            ],
        ),
    ]
