# Generated by Django 4.1.1 on 2024-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('round_number', models.IntegerField(default=1)),
                ('match_stadium', models.CharField(max_length=180)),
                ('match_city', models.CharField(max_length=180)),
            ],
        ),
    ]
