# Generated by Django 4.1.1 on 2024-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='match_date',
            field=models.DateTimeField(),
        ),
    ]
