# Generated by Django 5.0.6 on 2024-06-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_fixture_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='match_city',
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_logo',
            field=models.ImageField(default='logo2.png', upload_to='calendar'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_logo',
            field=models.ImageField(default='logo2.png', upload_to='calendar'),
        ),
    ]
