# Generated by Django 5.0.6 on 2024-06-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeagueHistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfixturefile',
            name='year',
        ),
    ]
